### ISSUE TITLE
DateTime crash

### ISSUE THREAD

**Issue by malhal** [chriswoodford/foursquare-php#15]
```
PHP Fatal error:  Uncaught exception 'Exception' with message 'DateTime::__construct(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone.' in /Users/mh/Development/Foursquare/vendor/thetwelvelabs/foursquare/lib/TheTwelve/Foursquare/EndpointGateway.php:36
Stack trace:
#0 /Users/mh/Development/Foursquare/vendor/thetwelvelabs/foursquare/lib/TheTwelve/Foursquare/EndpointGateway.php(36): DateTime->__construct('2013-10-23')
#1 /Users/mh/Development/Foursquare/vendor/thetwelvelabs/foursquare/lib/TheTwelve/Foursquare/ApiGatewayFactory.php(186): TheTwelve\Foursquare\EndpointGateway->__construct(Object(TheTwelve\Foursquare\HttpClient\CurlHttpClient))
#2 /Users/mh/Development/Foursquare/test.php(11): TheTwelve\Four in /Users/mh/Development/Foursquare/vendor/thetwelvelabs/foursquare/lib/TheTwelve/Foursquare/EndpointGateway.php on line 36
```

Here is what I had so far:

```
<?php

require_once __DIR__ . '/vendor/autoload.php';

$client = new \TheTwelve\Foursquare\HttpClient\CurlHttpClient();

$factory = new \TheTwelve\Foursquare\ApiGatewayFactory($client);

$factory->setClientCredentials('REDACTED', 'REDACTED');

$gateway = $factory->getVenuesGateway();

  $venues = $gateway->search(array(
    'll' => '40.727198,-73.992289',
    'query' => 'Starbucks',
    'radius' => 1000,
    'intent' => 'checkin'
  ));

print_r($venues);
```

**Comment by malhal** [comment]
had to set date.timezone in php.ini
